org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
loader_version_range=[1,)

mod_id=mineskate3
mod_name=MineSkate 3
mod_license=GPL-3.0-only
mod_version=0.1.0
mod_group_id=dev.mineskate3
