package dev.mineskate3;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

/** Skate sound events; the sounds themselves are generated by sounds/generate.py. */
public final class SkateSounds {
    private static final DeferredRegister<SoundEvent> SOUNDS =
            DeferredRegister.create(Registries.SOUND_EVENT, MineSkate3.MODID);

    public static final DeferredHolder<SoundEvent, SoundEvent> ROLL = sound("roll");
    public static final DeferredHolder<SoundEvent, SoundEvent> GRIND = sound("grind");
    public static final DeferredHolder<SoundEvent, SoundEvent> SLIDE = sound("slide");
    public static final DeferredHolder<SoundEvent, SoundEvent> POP = sound("pop");
    public static final DeferredHolder<SoundEvent, SoundEvent> LAND = sound("land");
    public static final DeferredHolder<SoundEvent, SoundEvent> LAND_HARD = sound("land_hard");
    public static final DeferredHolder<SoundEvent, SoundEvent> LOCK = sound("lock");
    public static final DeferredHolder<SoundEvent, SoundEvent> BAIL = sound("bail");
    public static final DeferredHolder<SoundEvent, SoundEvent> MARKER_PLACE = sound("marker_place");
    public static final DeferredHolder<SoundEvent, SoundEvent> MARKER_RETURN = sound("marker_return");

    private SkateSounds() {}

    private static DeferredHolder<SoundEvent, SoundEvent> sound(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(
                ResourceLocation.fromNamespaceAndPath(MineSkate3.MODID, name)));
    }

    public static void register(IEventBus modBus) {
        SOUNDS.register(modBus);
    }
}
