//! TU3 EScorableID enum metadata, table820862A8 (332 x24 bytes).
//! Numeric class/type relationships and native identifier spellings only.
//! Points, localization, timers and UI assets are loaded from owned data.
pub const IDENTIFIERS: [(&str, u32, usize); 332] = [
    ("fspowerslide", 0, 9),                  // 0
    ("bspowerslide", 0, 9),                  // 1
    ("nosemanual", 0, 8),                    // 2
    ("tailmanual", 0, 8),                    // 3
    ("fsrevert", 0, 11),                     // 4
    ("bsrevert", 0, 11),                     // 5
    ("bs_5_o", 1, 5),                        // 6
    ("bs_50_50", 1, 5),                      // 7
    ("bs_blunt", 1, 5),                      // 8
    ("bs_board", 1, 5),                      // 9
    ("bs_crook", 1, 5),                      // 10
    ("bs_feeble", 1, 5),                     // 11
    ("bs_lip", 1, 5),                        // 12
    ("bs_noseblunt", 1, 5),                  // 13
    ("bs_nosegrind", 1, 5),                  // 14
    ("bs_noseslide", 1, 5),                  // 15
    ("bs_overcrook", 1, 5),                  // 16
    ("bs_overwilly", 1, 5),                  // 17
    ("bs_salad", 1, 5),                      // 18
    ("bs_smith", 1, 5),                      // 19
    ("bs_tailslide", 1, 5),                  // 20
    ("bs_willy", 1, 5),                      // 21
    ("fs_5_o", 1, 5),                        // 22
    ("fs_50_50", 1, 5),                      // 23
    ("fs_blunt", 1, 5),                      // 24
    ("fs_board", 1, 5),                      // 25
    ("fs_crook", 1, 5),                      // 26
    ("fs_feeble", 1, 5),                     // 27
    ("fs_lip", 1, 5),                        // 28
    ("fs_noseblunt", 1, 5),                  // 29
    ("fs_nosegrind", 1, 5),                  // 30
    ("fs_noseslide", 1, 5),                  // 31
    ("fs_overcrook", 1, 5),                  // 32
    ("fs_overwilly", 1, 5),                  // 33
    ("fs_salad", 1, 5),                      // 34
    ("fs_smith", 1, 5),                      // 35
    ("fs_tailslide", 1, 5),                  // 36
    ("fs_willy", 1, 5),                      // 37
    ("grind5_o", 1, 5),                      // 38
    ("grind5050", 1, 5),                     // 39
    ("grindcrooks", 1, 5),                   // 40
    ("grindfeeble", 1, 5),                   // 41
    ("grindnose", 1, 5),                     // 42
    ("grindovercrooks", 1, 5),               // 43
    ("grindoverwilly", 1, 5),                // 44
    ("grindsalad", 1, 5),                    // 45
    ("grindsmith", 1, 5),                    // 46
    ("grindwilly", 1, 5),                    // 47
    ("slideblunt", 1, 5),                    // 48
    ("slideboard", 1, 5),                    // 49
    ("slidelip", 1, 5),                      // 50
    ("slidenblunt", 1, 5),                   // 51
    ("slidenose", 1, 5),                     // 52
    ("slidetail", 1, 5),                     // 53
    ("bsgrab", 2, 4),                        // 54
    ("bsgrab_down", 2, 4),                   // 55
    ("bsgrab_left", 2, 4),                   // 56
    ("bsgrab_right", 2, 4),                  // 57
    ("bsgrab_up", 2, 4),                     // 58
    ("christ_air", 2, 4),                    // 59
    ("coffin", 2, 4),                        // 60
    ("dblgrab", 2, 4),                       // 61
    ("fsgrab", 2, 4),                        // 62
    ("fsgrab_down", 2, 4),                   // 63
    ("fsgrab_left", 2, 4),                   // 64
    ("fsgrab_right", 2, 4),                  // 65
    ("fsgrab_up", 2, 4),                     // 66
    ("gnd_bsgrab", 2, 4),                    // 67
    ("gnd_dblgrab", 2, 4),                   // 68
    ("gnd_fsgrab", 2, 4),                    // 69
    ("mutegrab", 2, 4),                      // 70
    ("mutegrab_down", 2, 4),                 // 71
    ("mutegrab_left", 2, 4),                 // 72
    ("mutegrab_up", 2, 4),                   // 73
    ("nosegrab", 2, 4),                      // 74
    ("nosegrab_left", 2, 4),                 // 75
    ("nosegrab_right", 2, 4),                // 76
    ("rocketair", 2, 4),                     // 77
    ("stalegrab", 2, 4),                     // 78
    ("stalegrab_down", 2, 4),                // 79
    ("stalegrab_left", 2, 4),                // 80
    ("stalegrab_up", 2, 4),                  // 81
    ("tailgrab", 2, 4),                      // 82
    ("tailgrab_left", 2, 4),                 // 83
    ("tailgrab_right", 2, 4),                // 84
    ("360flip", 3, 2),                       // 85
    ("360hardflip", 3, 2),                   // 86
    ("360inwardheelflip", 3, 2),             // 87
    ("360popshuvit", 3, 2),                  // 88
    ("fs360popshuvit", 3, 2),                // 89
    ("fspopshuvit", 3, 2),                   // 90
    ("hardflip", 3, 2),                      // 91
    ("heelflip", 3, 2),                      // 92
    ("heelflip2", 3, 2),                     // 93
    ("heelflip3", 3, 2),                     // 94
    ("inwardheelflip", 3, 2),                // 95
    ("kickflip", 3, 2),                      // 96
    ("kickflip2", 3, 2),                     // 97
    ("kickflip3", 3, 2),                     // 98
    ("laserflip", 3, 2),                     // 99
    ("latebackfootheelflip", 3, 2),          // 100
    ("latebackfootkickflip", 3, 2),          // 101
    ("latebsshuv", 3, 2),                    // 102
    ("latefsshuv", 3, 2),                    // 103
    ("lateheelflip", 3, 2),                  // 104
    ("latekickflip", 3, 2),                  // 105
    ("n_360flip", 3, 2),                     // 106
    ("n_360hardflip", 3, 2),                 // 107
    ("n_360inwardheelflip", 3, 2),           // 108
    ("n_360popshuvit", 3, 2),                // 109
    ("n_fs360popshuvit", 3, 2),              // 110
    ("n_fspopshuvit", 3, 2),                 // 111
    ("n_hardflip", 3, 2),                    // 112
    ("n_heelflip", 3, 2),                    // 113
    ("n_heelflip2", 3, 2),                   // 114
    ("n_heelflip3", 3, 2),                   // 115
    ("n_inwardheelflip", 3, 2),              // 116
    ("n_kickflip", 3, 2),                    // 117
    ("n_kickflip2", 3, 2),                   // 118
    ("n_kickflip3", 3, 2),                   // 119
    ("n_laserflip", 3, 2),                   // 120
    ("n_popshuvit", 3, 2),                   // 121
    ("n_varialheelflip", 3, 2),              // 122
    ("n_varialkickflip", 3, 2),              // 123
    ("popshuvit", 3, 2),                     // 124
    ("varialheelflip", 3, 2),                // 125
    ("varialkickflip", 3, 2),                // 126
    ("nollie", 4, 1),                        // 127
    ("ollie", 4, 1),                         // 128
    ("air_horizontal_distance", 5, 0),       // 129
    ("air_height_to_peak", 5, 0),            // 130
    ("air_total_height_gain", 5, 0),         // 131
    ("air_player_spin", 5, 0),               // 132
    ("air_player_flip", 5, 0),               // 133
    ("heelflip4", 3, 2),                     // 134
    ("kickflip4", 3, 2),                     // 135
    ("n_heelflip4", 3, 2),                   // 136
    ("n_kickflip4", 3, 2),                   // 137
    ("nofoot_air", 2, 4),                    // 138
    ("fs_handplant", 6, 6),                  // 139
    ("fs_handplant_up", 6, 6),               // 140
    ("fs_handplant_right", 6, 6),            // 141
    ("fs_handplant_left", 6, 6),             // 142
    ("fs_handplant_down", 6, 6),             // 143
    ("fs_handplant_onefoot_front", 6, 6),    // 144
    ("fs_handplant_onefoot_back", 6, 6),     // 145
    ("fs_handplant_nofoot", 6, 6),           // 146
    ("fs_handplant_to_fakie", 6, 6),         // 147
    ("fs_handplant_to_revert", 6, 6),        // 148
    ("bs_handplant", 6, 6),                  // 149
    ("bs_handplant_up", 6, 6),               // 150
    ("bs_handplant_right", 6, 6),            // 151
    ("bs_handplant_left", 6, 6),             // 152
    ("bs_handplant_down", 6, 6),             // 153
    ("bs_handplant_onefoot_front", 6, 6),    // 154
    ("bs_handplant_onefoot_back", 6, 6),     // 155
    ("bs_handplant_nofoot", 6, 6),           // 156
    ("bs_handplant_to_fakie", 6, 6),         // 157
    ("bs_handplant_to_revert", 6, 6),        // 158
    ("bs_handplant_mount", 6, 6),            // 159
    ("bs_handplant_dismount", 6, 6),         // 160
    ("bs_handplant_to_flat", 6, 6),          // 161
    ("fs_onefoot_right", 2, 4),              // 162
    ("fs_backfoot", 2, 4),                   // 163
    ("bs_onefoot_front", 2, 4),              // 164
    ("bs_onefoot_behind", 2, 4),             // 165
    ("nosegrab_onefoot_front", 2, 4),        // 166
    ("nosegrab_onefoot_behind", 2, 4),       // 167
    ("tailgrab_onefoot_front", 2, 4),        // 168
    ("tailgrab_onefoot_behind", 2, 4),       // 169
    ("ollie_onefoot_front", 4, 1),           // 170
    ("ollie_onefoot_back", 4, 1),            // 171
    ("tailgrab_airwalk", 2, 4),              // 172
    ("fsgrab_fingerflip", 4, 3),             // 173
    ("bsgrab_fingerflip", 4, 3),             // 174
    ("nosegrab_fingerflip", 4, 3),           // 175
    ("tailgrab_fingerflip", 4, 3),           // 176
    ("mutegrab_fingerflip", 4, 3),           // 177
    ("stalegrab_fingerflip", 4, 3),          // 178
    ("fsgrabvarial_fingerflip", 4, 3),       // 179
    ("bsgrabvarial_fingerflip", 4, 3),       // 180
    ("fs_rock_n_roll", 1, 5),                // 181
    ("bs_rock_n_roll", 1, 5),                // 182
    ("fakie_rock", 1, 5),                    // 183
    ("dropin", 1, 5),                        // 184
    ("dropin_fs_revert", 1, 5),              // 185
    ("dropin_bs_revert", 1, 5),              // 186
    ("crailgrab", 2, 4),                     // 187
    ("crailgrab_left", 2, 4),                // 188
    ("crailgrab_right", 2, 4),               // 189
    ("seatbeltgrab", 2, 4),                  // 190
    ("seatbeltgrab_left", 2, 4),             // 191
    ("seatbeltgrab_right", 2, 4),            // 192
    ("fs_50_50_fsgrab", 1, 5),               // 193
    ("fs_50_50_bsgrab", 1, 5),               // 194
    ("fs_nosegrind_tailgrab", 1, 5),         // 195
    ("fs_nosegrind_bsgrab", 1, 5),           // 196
    ("fs_crook_tailgrab", 1, 5),             // 197
    ("fs_crook_bsgrab", 1, 5),               // 198
    ("bs_crook_tailgrab", 1, 5),             // 199
    ("bs_crook_bsgrab", 1, 5),               // 200
    ("fs_noseslide_tailgrab", 1, 5),         // 201
    ("bs_noseslide_tailgrab", 1, 5),         // 202
    ("fs_noseblunt_tailgrab", 1, 5),         // 203
    ("bs_noseblunt_tailgrab", 1, 5),         // 204
    ("fs_5_o_fsgrab", 1, 5),                 // 205
    ("fs_5_o_nosegrab", 1, 5),               // 206
    ("fs_salad_fsgrab", 1, 5),               // 207
    ("fs_salad_nosegrab", 1, 5),             // 208
    ("bs_salad_fsgrab", 1, 5),               // 209
    ("bs_salad_nosegrab", 1, 5),             // 210
    ("fs_tailslide_nosegrab", 1, 5),         // 211
    ("bs_tailslide_nosegrab", 1, 5),         // 212
    ("fs_blunt_tailgrab", 1, 5),             // 213
    ("bs_blunt_tailgrab", 1, 5),             // 214
    ("fsboneless", 4, 12),                   // 215
    ("bsboneless", 4, 12),                   // 216
    ("fsfastplant", 4, 12),                  // 217
    ("bsfastplant", 4, 12),                  // 218
    ("bsgrab_fs_footplant", 4, 13),          // 219
    ("bsgrab_bs_footplant", 4, 13),          // 220
    ("fsgrab_fs_footplant", 4, 13),          // 221
    ("fsgrab_bs_footplant", 4, 13),          // 222
    ("nosegrab_fs_footplant", 4, 13),        // 223
    ("nosegrab_bs_footplant", 4, 13),        // 224
    ("tailgrab_fs_footplant", 4, 13),        // 225
    ("tailgrab_bs_footplant", 4, 13),        // 226
    ("ollie_fs_footplant", 4, 13),           // 227
    ("ollie_bs_footplant", 4, 13),           // 228
    ("nocomply", 4, 7),                      // 229
    ("no_comply_fs180", 4, 7),               // 230
    ("no_comply_bs180", 4, 7),               // 231
    ("no_comply_fs360", 4, 7),               // 232
    ("no_comply_bs360", 4, 7),               // 233
    ("hippyjump", 4, 10),                    // 234
    ("hippyjump_fs180", 4, 10),              // 235
    ("hippyjump_bs180", 4, 10),              // 236
    ("air_metric", 5, 0),                    // 237
    ("fsgrabtostalegrab_fingerflip", 4, 3),  // 238
    ("bsgrabtomutegrab_fingerflip", 4, 3),   // 239
    ("stalegrabtofsgrab_fingerflip", 4, 3),  // 240
    ("mutegrabtobsgrab_fingerflip", 4, 3),   // 241
    ("bs_50_50_fsgrab", 1, 5),               // 242
    ("bs_50_50_bsgrab", 1, 5),               // 243
    ("bs_nosegrind_tailgrab", 1, 5),         // 244
    ("bs_nosegrind_bsgrab", 1, 5),           // 245
    ("bs_5_o_fsgrab", 1, 5),                 // 246
    ("bs_5_o_nosegrab", 1, 5),               // 247
    ("fs_overcrook_tailgrab", 1, 5),         // 248
    ("fs_overcrook_bsgrab", 1, 5),           // 249
    ("bs_overcrook_tailgrab", 1, 5),         // 250
    ("bs_overcrook_bsgrab", 1, 5),           // 251
    ("superman", 2, 4),                      // 252
    ("generic_metric", 5, 0),                // 253
    ("nosegrab_airwalk", 2, 4),              // 254
    ("seatbelttonose_fingerflip", 4, 3),     // 255
    ("crailtotail_fingerflip", 4, 3),        // 256
    ("fs_board_double", 1, 5),               // 257
    ("fs_board_tail", 1, 5),                 // 258
    ("fs_board_nose", 1, 5),                 // 259
    ("bs_board_double", 1, 5),               // 260
    ("bs_board_tail", 1, 5),                 // 261
    ("bs_board_nose", 1, 5),                 // 262
    ("fs_lip_double", 1, 5),                 // 263
    ("fs_lip_tail", 1, 5),                   // 264
    ("fs_lip_nose", 1, 5),                   // 265
    ("bs_lip_double", 1, 5),                 // 266
    ("bs_lip_tail", 1, 5),                   // 267
    ("bs_lip_nose", 1, 5),                   // 268
    ("bs_darkslide", 1, 5),                  // 269
    ("fs_darkslide", 1, 5),                  // 270
    ("bs_darkslide_double", 1, 5),           // 271
    ("bs_darkslide_tail", 1, 5),             // 272
    ("bs_darkslide_nose", 1, 5),             // 273
    ("fs_darkslide_double", 1, 5),           // 274
    ("fs_darkslide_tail", 1, 5),             // 275
    ("fs_darkslide_nose", 1, 5),             // 276
    ("heelflip_underflip", 3, 2),            // 277
    ("heelflip2_underflip", 3, 2),           // 278
    ("heelflip3_underflip", 3, 2),           // 279
    ("heelflip4_underflip", 3, 2),           // 280
    ("kickflip_underflip", 3, 2),            // 281
    ("kickflip2_underflip", 3, 2),           // 282
    ("kickflip3_underflip", 3, 2),           // 283
    ("kickflip4_underflip", 3, 2),           // 284
    ("n_heelflip_underflip", 3, 2),          // 285
    ("n_heelflip2_underflip", 3, 2),         // 286
    ("n_heelflip3_underflip", 3, 2),         // 287
    ("n_heelflip4_underflip", 3, 2),         // 288
    ("n_kickflip_underflip", 3, 2),          // 289
    ("n_kickflip2_underflip", 3, 2),         // 290
    ("n_kickflip3_underflip", 3, 2),         // 291
    ("n_kickflip4_underflip", 3, 2),         // 292
    ("popshuvit_underflip", 3, 2),           // 293
    ("fspopshuvit_underflip", 3, 2),         // 294
    ("n_popshuvit_underflip", 3, 2),         // 295
    ("n_fspopshuvit_underflip", 3, 2),       // 296
    ("heelflip_darkcatch", 3, 2),            // 297
    ("heelflip2_darkcatch", 3, 2),           // 298
    ("heelflip3_darkcatch", 3, 2),           // 299
    ("heelflip4_darkcatch", 3, 2),           // 300
    ("kickflip_darkcatch", 3, 2),            // 301
    ("kickflip2_darkcatch", 3, 2),           // 302
    ("kickflip3_darkcatch", 3, 2),           // 303
    ("kickflip4_darkcatch", 3, 2),           // 304
    ("n_heelflip_darkcatch", 3, 2),          // 305
    ("n_heelflip2_darkcatch", 3, 2),         // 306
    ("n_heelflip3_darkcatch", 3, 2),         // 307
    ("n_heelflip4_darkcatch", 3, 2),         // 308
    ("n_kickflip_darkcatch", 3, 2),          // 309
    ("n_kickflip2_darkcatch", 3, 2),         // 310
    ("n_kickflip3_darkcatch", 3, 2),         // 311
    ("n_kickflip4_darkcatch", 3, 2),         // 312
    ("360flip_darkcatch", 3, 2),             // 313
    ("360hardflip_darkcatch", 3, 2),         // 314
    ("360inwardheelflip_darkcatch", 3, 2),   // 315
    ("laserflip_darkcatch", 3, 2),           // 316
    ("n_360flip_darkcatch", 3, 2),           // 317
    ("n_360hardflip_darkcatch", 3, 2),       // 318
    ("n_360inwardheelflip_darkcatch", 3, 2), // 319
    ("n_laserflip_darkcatch", 3, 2),         // 320
    ("darktolightbsshuv", 3, 2),             // 321
    ("darktolightfsshuv", 3, 2),             // 322
    ("darktolightheelflip", 3, 2),           // 323
    ("darktolightkickflip", 3, 2),           // 324
    ("darkslideout_bsstraight", 3, 2),       // 325
    ("darkslideout_bsleft", 3, 2),           // 326
    ("darkslideout_bsright", 3, 2),          // 327
    ("darkslideout_fsstraight", 3, 2),       // 328
    ("darkslideout_fsleft", 3, 2),           // 329
    ("darkslideout_fsright", 3, 2),          // 330
    ("lateflip_darkcatch", 3, 2),            // 331
];
